apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enable-gitops-console-plugin
rules:
  - apiGroups: ["operator.openshift.io"]
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
      - label
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enable-gitops-console-plugin
subjects:
  - kind: ServiceAccount
    name: enable-gitops-console-plugin
    namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enable-gitops-console-plugin
