apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

resources:
  - enable-console-plugin-job.yaml
  - enable-console-plugin-rbac.yaml
  - enable-console-plugin-sa.yaml
  - openshift-gitops-operator-subscription.yaml
